function [fitresult, gof] = createFit2(ax, ay)
%CREATEFIT2(AX,AY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : ax
%      Y Output: ay
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Feb-2022 14:09:34


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( ax, ay );

% Set up fittype and options.
ft = fittype( 'sin2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [1232.12471035098 0.00196472336059399 -0.526721888427565 3396.27449378602 0.00392944672118798 0.0391119890406531];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'ay vs. ax', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'ax', 'Interpreter', 'none' );
ylabel( 'ay', 'Interpreter', 'none' );
grid on


